- name: copy the project folder
  copy:
    src: "{{ project_src }}"
    dest: "{{ project_dest }}"
    mode: 0755

- name: Install docker module for python
  pip:
    name: docker
    virtualenv: "{{ virtual_env }}"

- name: run make command
  make:
    chdir: "{{ work_dir }}"